spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
        # native:
          # search-locations: "file:///C://Users//princ//Documents//config"
          # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/princejains1198/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "704whSFmE3d1rice5kqDIgynznL4lfHA1F/rh+btgnI="

server:
  port: 8071

